import { test, expect } from '@playwright/test';
import { login,createSection,expectPoints,recordScore } from './ui-helpers.js';
test('two students create/join, save scores, revise shared weights and delete owner data',async({page,context},testInfo)=>{
  await login(page,'browser-creator-'+testInfo.project.name);
  await createSection(page);await expectPoints(page,0);
  const code=(await page.getByText(/Join code:/).textContent()).match(/Join code:\s*([A-Z0-9]{6})/)[1];
  await recordScore(page,'Midterm',80);await expectPoints(page,32);
  const friend=await context.newPage();await login(friend,'browser-classmate-'+testInfo.project.name);
  await friend.getByRole('navigation').getByRole('button',{name:'Add course',exact:true}).click();
  await friend.getByRole('button',{name:/Join a section/}).click();
  await friend.getByLabel('Section join code',{exact:true}).fill(code);
  await friend.getByRole('button',{name:'Join section',exact:true}).click();
  await friend.getByRole('button',{name:'Go to course'}).click();await expectPoints(friend,0);
  await expect(friend.getByRole('button',{name:'Correct shared weights'})).toHaveCount(0);
  await recordScore(friend,'Midterm',60);await expectPoints(friend,24);
  await page.getByRole('button',{name:'Correct shared weights'}).click();
  await page.getByLabel('Midterm corrected weight').fill('30');
  await expect(page.getByText('Add 10% to reach 100%.')).toBeVisible();
  await expect(page.getByRole('button',{name:'Save corrected weights'})).toBeDisabled();
  await page.getByLabel('Final corrected weight').fill('70');
  await page.getByRole('checkbox',{name:/I checked these corrected weights/}).check();
  await page.getByRole('button',{name:'Save corrected weights'}).click();await expectPoints(page,24);
  await expect(page.getByText('Raw marks: 80 / 100')).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('course-revision.png'),fullPage:true});
  await page.getByRole('button',{name:/Target grade A/}).click();
  await page.getByRole('button',{name:'Save target and calculate'}).click();
  await expect(page.getByText(/Required on remaining assessments:/)).toContainText('80%');
  await page.screenshot({path:testInfo.outputPath('target-grade.png'),fullPage:true});
  await friend.getByRole('button',{name:'Refresh course and weights'}).click();await expectPoints(friend,18);
  await expect(friend.getByText(/The creator changed grading weights/)).toBeVisible();
  await expect(friend.getByText('Raw marks: 60 / 100')).toBeVisible();
  await page.getByRole('navigation').getByRole('button',{name:'Privacy'}).click();
  await page.getByRole('checkbox',{name:/I confirm deletion/}).check();
  await page.getByRole('button',{name:'Delete my data',exact:true}).click();
  await expect(page.getByRole('button',{name:'Agree and continue'})).toBeVisible();
  await expect(page.getByText('Raw marks: 80 / 100')).toHaveCount(0);
  await friend.getByRole('button',{name:'Refresh course and weights'}).click();await expectPoints(friend,18);await friend.close();
});
